################################################################################################
#            iCraftPatches by iPodHacks142 (iCraft) & Lee (ModdedMinecraft)                    #
#                                  For the Big Dig Modpack                                     #
################################################################################################

################################################################################################
# Items that can't be clicked on a block inside a claim.                                       #
################################################################################################
RightClickBlockInClaim:
  - '7783' # Chalk
  - '7784' # Chalk
  - '7785' # Chalk
  - '7786' # Chalk
  - '6602' # Block Replacer
  - '6601' # Block Mover
  - '6613' # Target Card
  - '11273' # Paintbrush
  - '5588' # PortaSpawner
  - '7616' # Beach Chair
  - '7685' # Umbrella
  - '7071' # Flag
  - '6610' # Portable Ender Porter
  - '6606' # Entity Mover
  - '11510' # Egg
  - '23797' # Flans Flag
  - '11277' # Squeegee
  - '7583' # Hammer
  - '7759' # Surf Board
  - '10257' # Hamster Ball
  - '7789' # Broom
  - '7067' # Buggy
  - '11272' # Luggage
  - '10729' # Crescent Hammer
  - '10720' # BattleWrench
  - '7094' # Standard Wrench
  
################################################################################################
# Items that can't be clicked in the air in a 16 block range around a claim.                   #
################################################################################################
ClickAroundClaim:
  - '6958' # TMPP Launcher
  - '6957' # Nyan Pig Launcher
  
################################################################################################
# Items that can't be clicked in the air anywhere in the world.                                #
################################################################################################
AirclickWorld:
  - '999' # Undefined

################################################################################################
# Items that can't be placed near claims                                                       #
################################################################################################
PlaceNearClaim:
  - '999:*' # Undefined

################################################################################################
# Minium/Philosophers Stone ID's                                                               #
################################################################################################
EEStoneID:
  - '10357' # Micro Blocks

################################################################################################
# Minium/Philosophers Stone ID's                                                               #
################################################################################################
HelmID:
  - '656:*' # Helm
  
SyncWarning:
  - '6757:0'
  - '6757:1'
